### ISSUE TITLE
AdjustTokenPrivileges failed, error code: 1300

### ISSUE THREAD

**Issue by tatzio** [Witek902/Caissa#14]
When running caissa-1.13.1-x64-avx2-bmi2.exe under Win11 I get following output:
```
AdjustTokenPrivileges failed, error code: 1300
Caissa 1.13.1 AVX2 by Michal Witanowski
info string Using embedded neural network
```

Engine seems to be working fine...

EDIT: do not have this on other machine with Win10
also found this, but not sure it this is related: https://devblogs.microsoft.com/oldnewthing/20211126-00/?p=105973

**Comment by Witek902** [comment]
I will probably remove this error in next release, as it's not really an error.
It means that the engine failed to enable [large pages feature](https://learn.microsoft.com/en-us/windows/win32/memory/large-page-support). It should give small speedup when using big transposition table. You either need to run it with admin rights (not recommended) or add a privilege in security settings:
1. run secpol.msc
2. go to Security Settings > Local Policies > User Rights Assignment
3. double click on "Lock pages in memory" and add your user you log in with to Windows

I think many other engines also try to use the feature, but silently ignore it.

**Comment by Witek902** [comment]
Fixed in 1.14

**Comment by tatzio** [comment]
Still getting same warning in 1.15:
```
AdjustTokenPrivileges failed, error code: 1300
Caissa 1.15 BMI2 by Michal Witanowski
info string Using embedded neural network
```

Even if I run console with admin rights.
Just FYI, not that it bothers me in any way.

**Comment by Witek902** [comment]
My bad, fixed in 1.16

**Comment by tatzio** [comment]
thanks, works perfectly now
